import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {sceneSpec} from './cosmic-model.js';
function earthTexture(){const c=document.createElement('canvas');c.width=256;c.height=128;const x=c.getContext('2d');if(!x)return null;const d=x.createImageData(256,128);for(let j=0;j<128;j++)for(let i=0;i<256;i++){const lat=(j/128-.5)*Math.PI,lon=i/256*Math.PI*2;const n=Math.sin(lon*3+Math.sin(lat*5))+Math.sin(lat*6+lon*.6);const land=n>.6;const polar=Math.abs(lat)>1.3;let color=polar?[194,217,227]:land?[77,126,101]:[28,83,127];const cloud=Math.sin(lon*13+lat*9)*Math.cos(lat*17-lon*3)>.77;const k=(j*256+i)*4;color.forEach((v,t)=>d.data[k+t]=cloud?v*.5+115:v);d.data[k+3]=255;}x.putImageData(d,0,0);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
export function createCosmicView(host,{onMode,reducedMotion=false,force2d=false}={}){
 host.dataset.reducedMotion=String(reducedMotion);let index=0,renderer=null,scene,camera,controls,group,raf=0,progress=1,last=0,disposed=false,active=true;const overlay=document.createElement('div');overlay.className='cosmic-labels';overlay.setAttribute('aria-hidden','true');host.append(overlay);const fallback=document.createElement('canvas');fallback.className='cosmic-2d';fallback.setAttribute('aria-hidden','true');host.prepend(fallback);let ctx=null;try{ctx=fallback.getContext('2d');}catch{}
 function draw2d(){if(!ctx||renderer)return;const w=host.clientWidth||800,h=host.clientHeight||490,dpr=Math.min(globalThis.devicePixelRatio||1,1.5);fallback.width=w*dpr;fallback.height=h*dpr;fallback.style.width=w+'px';fallback.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const s=Math.min(w/23,h/23),spec=sceneSpec(index),project=p=>[w/2+p.x*s,h/2+(p.z*.35-p.y*.8)*s];
 let seed=17;for(let n=0;n<100;n++){seed=seed*16807%2147483647;const x=seed/2147483647*w;seed=seed*16807%2147483647;ctx.fillStyle='#adbed144';ctx.fillRect(x,seed/2147483647*h,1,1);}
 for(const r of spec.orbits){ctx.strokeStyle='#7795af44';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(w/2,h/2,r*s,r*s*.35,0,0,Math.PI*2);ctx.stroke();}
 for(const line of spec.lines||[]){const [x,y]=project({x:line[0],y:line[1],z:line[2]}),[x2,y2]=project({x:line[3],y:line[4],z:line[5]});ctx.strokeStyle='#d4b27b88';ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();ctx.setLineDash([]);}
 for(const p of spec.points){const [x,y]=project(p);ctx.fillStyle=p.color;ctx.globalAlpha=.5+(p.size||.05)*4;ctx.beginPath();ctx.arc(x,y,Math.max(.6,(p.size||.04)*s),0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
 for(const p of spec.spheres){const [x,y]=project(p),r=Math.max(2,p.r*s),grad=ctx.createRadialGradient(x-r*.35,y-r*.4,r*.05,x,y,r);grad.addColorStop(0,p.color);grad.addColorStop(.6,p.color);grad.addColorStop(1,'#07101c');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(index===0){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();ctx.globalAlpha=.55;ctx.fillStyle='#91b2a1';for(let a=0;a<5;a++){ctx.beginPath();ctx.ellipse(x+Math.sin(a*2.3)*r*.55,y+Math.cos(a*1.8)*r*.5,r*.20,r*.11,a,0,Math.PI*2);ctx.fill();}ctx.restore();ctx.strokeStyle='#82caff77';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,r+3,0,Math.PI*2);ctx.stroke();}}
 overlay.replaceChildren();for(const p of [...spec.spheres.filter(p=>p.label).map(p=>({...p,text:p.label,y:p.y-p.r-.5})),...spec.labels]){const [x,y]=project(p),el=document.createElement('span');el.textContent=p.text;el.style.left=Math.max(10,Math.min(w-10,x))+'px';el.style.top=y+'px';overlay.append(el);}
 }
 function fallbackMode(){if(renderer){renderer.dispose();renderer.domElement.remove();renderer=null;}cancelAnimationFrame(raf);fallback.hidden=false;onMode?.('2d');draw2d();}
 try{if(force2d)throw Error('2D requested');renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;host.prepend(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','宇宙尺度三維示意。拖曳改變視角；尺度請用下方滑桿或步進按鈕。方向鍵亦可切換尺度。');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(46,1,.1,200);camera.position.set(0,13,23);controls=new OrbitControls(camera,renderer.domElement);renderer.domElement.style.touchAction='pan-y';controls.enableDamping=true;controls.enableZoom=false;controls.enablePan=false;controls.rotateSpeed=.55;scene.add(new THREE.AmbientLight('#ddefff',2));const light=new THREE.DirectionalLight('#e1efff',3);light.position.set(-5,5,8);scene.add(light);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fallbackMode();});fallback.hidden=true;onMode?.('3d');}catch{fallbackMode();}
 function disposeGroup(){if(!group)return;group.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});scene.remove(group);}
 function rebuild(){if(!renderer){draw2d();return;}disposeGroup();overlay.replaceChildren();group=new THREE.Group();const spec=sceneSpec(index);for(const p of spec.spheres){const material=new THREE.MeshStandardMaterial({color:p.color,roughness:1,emissive:p.color,emissiveIntensity:index===0?0:.25,map:index===0?earthTexture():null});if(index===0)material.color.set('#ffffff');const mesh=new THREE.Mesh(new THREE.SphereGeometry(p.r,40,26),material);mesh.position.set(p.x,p.y,p.z);group.add(mesh);}
 if(spec.points.length){const g=new THREE.BufferGeometry(),positions=[],colors=[];for(const p of spec.points){positions.push(p.x,p.y,p.z);const c=new THREE.Color(p.color);colors.push(c.r,c.g,c.b);}g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));group.add(new THREE.Points(g,new THREE.PointsMaterial({size:index===4?.11:.09,vertexColors:true,transparent:true,opacity:.85,sizeAttenuation:true})));}
 for(const r of spec.orbits){const pts=Array.from({length:129},(_,i)=>new THREE.Vector3(Math.cos(i/128*Math.PI*2)*r,0,Math.sin(i/128*Math.PI*2)*r));group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:'#68869f',transparent:true,opacity:.4})));}
 for(const line of spec.lines||[])group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...line.slice(0,3)),new THREE.Vector3(...line.slice(3))]),new THREE.LineBasicMaterial({color:'#ad9274',transparent:true,opacity:.7})));
 for(const p of [...spec.spheres.filter(p=>p.label).map(p=>({...p,text:p.label,y:p.y-p.r-.5})),...spec.labels]){const el=document.createElement('span');el.textContent=p.text;overlay.append(el);el._point=new THREE.Vector3(p.x,p.y,p.z);}
 scene.add(group);progress=reducedMotion?1:0;last=performance.now();}
 function resize(){if(renderer){const w=host.clientWidth||800,h=host.clientHeight||490;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=camera.aspect<1?65:46;camera.updateProjectionMatrix();}else draw2d();}
 const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;observer?.observe(host);function frame(now){if(disposed||!renderer)return;raf=requestAnimationFrame(frame);if(!active||document.hidden)return;const dt=Math.min((now-last)/1000,.05);last=now;progress=Math.min(1,progress+dt*1.8);if(group)group.scale.setScalar(.78+.22*(1-Math.pow(1-progress,3)));controls.update();camera.updateMatrixWorld();for(const el of overlay.children){const v=el._point.clone().multiplyScalar(group?.scale.x||1).project(camera);el.style.left=(v.x*.5+.5)*host.clientWidth+'px';el.style.top=(-v.y*.5+.5)*host.clientHeight+'px';el.hidden=v.z>1;}renderer.render(scene,camera);}
 rebuild();resize();if(renderer)raf=requestAnimationFrame(frame);const visible=typeof IntersectionObserver!=='undefined'?new IntersectionObserver(entries=>active=entries[0].isIntersecting):null;visible?.observe(host);
 return {setStage(n){index=n;rebuild();},resetView(){if(camera){camera.position.set(0,13,23);controls.target.set(0,0,0);controls.update();}},dispose(){disposed=true;cancelAnimationFrame(raf);observer?.disconnect();visible?.disconnect();controls?.dispose();if(renderer){disposeGroup();renderer.dispose();}host.replaceChildren();}};
}
