import data from './cosmic-data.json';
import {validStage,scaledDistanceMetres} from './cosmic-model.js';
import {createCosmicView} from './cosmic-scene.js';
export function initCosmic(){
 const $=s=>document.querySelector(s),{stages,constants:c}=data;let index=0;const reducedMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
 $('#cosmic-steps').innerHTML=stages.map((s,i)=>`<button data-cosmic="${i}" aria-current="false"><small>${String(i+1).padStart(2,'0')}</small>${s.name}</button>`).join('');
 const view=createCosmicView($('#cosmic-stage'),{reducedMotion,force2d:new URLSearchParams(location.search).has('no3d'),onMode:mode=>{$('#cosmic-mode').textContent=mode==='3d'?'✦ 3D 尺度導覽':'✦ 2D 尺度導覽';}});
 function show(next,save=false){index=validStage(next);const s=stages[index];view.setStage(index);$('#cosmic-counter').textContent=`${String(index+1).padStart(2,'0')} / 07`;$('#cosmic-scale').textContent=s.scaleLabel;$('#cosmic-range').value=String(index);$('#cosmic-range').setAttribute('aria-valuetext',s.name+'，'+s.scaleLabel);$('#cosmic-range-name').textContent=s.name;$('#cosmic-prev').disabled=index===0;$('#cosmic-next').disabled=index===stages.length-1;document.querySelectorAll('[data-cosmic]').forEach(b=>b.setAttribute('aria-current',Number(b.dataset.cosmic)===index?'step':'false'));$('#cosmic-detail').innerHTML=`<p class="eyebrow">${String(index+1).padStart(2,'0')} / ${s.kicker}</p><h3>${s.title}</h3><div class="cosmic-distance">${s.scaleLabel}</div><div class="cosmic-copy">${s.facts.map(f=>`<p>${f}</p>`).join('')}</div><p class="cosmic-caution">${s.caution}</p><div class="cosmic-light"><span>光與時間</span>${s.lightTime}</div><a class="source" href="${s.source}" target="_blank" rel="noopener">查看官方資料 ↗</a>${s.sources?.length>1?`<div class="cosmic-extra-sources">${s.sources.slice(1).map((url,i)=>`<a href="${url}" target="_blank" rel="noopener">延伸來源 ${i+1} ↗</a>`).join(' · ')}</div>`:''}`;if(save){const u=new URL(location.href);u.searchParams.set('cosmic',String(index));if(u.href!==location.href)history.pushState(null,'',u);}}
 $('#cosmic-prev').addEventListener('click',()=>show(index-1,true));$('#cosmic-next').addEventListener('click',()=>show(index+1,true));document.querySelectorAll('[data-cosmic]').forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.cosmic),true)));$('#cosmic-range').addEventListener('input',e=>show(Number(e.target.value),false));$('#cosmic-range').addEventListener('change',()=>show(index,true));$('#cosmic-reset').addEventListener('click',()=>{view.resetView();show(0,true);});$('#return-solar').addEventListener('click',()=>{document.querySelector('#planet-nav [data-body=earth]').click();});
 $('#cosmic-stage').addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight'||e.key==='ArrowUp')next=Math.min(stages.length-1,index+1);if(e.key==='ArrowLeft'||e.key==='ArrowDown')next=Math.max(0,index-1);if(e.key==='Home')next=0;if(e.key==='End')next=stages.length-1;if(next!==undefined){e.preventDefault();show(next,true);}});$('#cosmic-stage').tabIndex=0;
 window.addEventListener('popstate',()=>show(validStage(new URLSearchParams(location.search).get('cosmic')),false));
 const num=n=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:1}).format(n),distance=m=>m>=1000?`${num(m/1000)} 公里`:`${num(m)} 公尺`;
 function ruler(){const cm=Number($('#earth-cm').value);$('#earth-cm-value').value=cm.toFixed(1)+' cm';const get=km=>scaledDistanceMetres(km,c.earthDiameterKm,cm);$('#ruler-results').innerHTML=[['太陽直徑',distance(get(1400000)),'太陽直徑採約 140 萬公里'],['模型地球到太陽',distance(get(c.auKm)),'真實代表距離：1 AU'],['模型太陽到海王星軌道',distance(get(c.auKm*c.neptuneOrbitAU)),'真實軌道半長軸：約 30 AU'],['模型太陽到比鄰星',distance(get(c.lightYearKm*c.proximaDistanceLy)),'真實距離：約 4.24 光年']].map(([name,value,note])=>`<div class="ruler-result"><span>${name}</span><b>${value}</b><small>${note}</small></div>`).join('');}
 $('#earth-cm').addEventListener('input',ruler);ruler();show(validStage(new URLSearchParams(location.search).get('cosmic')),false);
 return {show,index:()=>index,dispose:()=>view.dispose()};
}
