// Original procedural teaching geometry, never an observed catalogue or a real sky map.
function random(seed){let s=seed;return ()=>{s=s*16807%2147483647;return s/2147483647;};}
const galaxy=(x,y,z,r,kind=0,angle=0)=>({x,y,z,r,kind,angle});
export function localGroupSpec(){const rand=random(335),galaxies=[galaxy(-3,0,0,1.8,0,-.3),galaxy(3.2,1.8,-1,2.4,0,.55),galaxy(5.8,-2,1,.95,0,-.7)];for(let i=0;i<25;i++){const a=rand()*Math.PI*2,r=2.5+rand()*6;galaxies.push(galaxy(Math.cos(a)*r,Math.sin(a)*r*.7,(rand()-.5)*4,.10+rand()*.23,i%3,rand()*Math.PI));}return {spheres:[],points:[],orbits:[],galaxies,labels:[{x:-3,y:2.1,z:0,text:'銀河系'},{x:3.2,y:4.6,z:-1,text:'仙女座星系'},{x:5.8,y:-3.5,z:1,text:'三角座星系'},{x:-5,y:-4.5,z:0,text:'周圍還有許多矮星系（數量為示意）'}]};}
export function neighborhoodSpec(){const rand=random(919),galaxies=[],centers=[{x:0,y:0,z:0,n:12,r:1.1,name:'本星系群'},{x:-7,y:4,z:1,n:18,r:1.7,name:'M81 星系群'},{x:-6,y:-4,z:-1,n:20,r:2,name:'半人馬 A / M83 群'},{x:6.3,y:1.7,z:0,n:65,r:3.3,name:'室女座星系團'}];for(const c of centers){galaxies.push(galaxy(c.x,c.y,c.z,c.n>40?.65:.50,c.n>40?1:0));for(let i=0;i<c.n;i++){const a=rand()*Math.PI*2,r=Math.sqrt(rand())*c.r;galaxies.push(galaxy(c.x+Math.cos(a)*r,c.y+Math.sin(a)*r*.85,c.z+(rand()-.5)*2,.1+rand()*.23,i%3,rand()*Math.PI));}}return {spheres:[],points:[],orbits:[],galaxies,labels:centers.map(c=>({x:c.x,y:c.y+c.r+1,z:c.z,text:c.name})),highlights:centers.map(c=>({...c,r:c.r+1}))};}
export function cosmicWebSpec(seed=453,universe=false){const rand=random(seed),nodes=Array.from({length:22},()=>({x:(rand()-.5)*24,y:(rand()-.5)*16,z:(rand()-.5)*15})),edges=[],points=[],galaxies=[];const seen=new Set();for(let i=0;i<nodes.length;i++){const closest=nodes.map((b,j)=>({j,d:Math.hypot(b.x-nodes[i].x,b.y-nodes[i].y,b.z-nodes[i].z)})).filter(p=>p.j!==i).sort((a,b)=>a.d-b.d).slice(0,3);for(const {j} of closest){const key=[i,j].sort((a,b)=>a-b).join('-');if(seen.has(key))continue;seen.add(key);edges.push([nodes[i],nodes[j]]);}}
 for(const [a,b] of edges){for(let j=0;j<24;j++){const t=j/23,w=.10+Math.sin(t*Math.PI)*.35;points.push({x:a.x+(b.x-a.x)*t+(rand()-.5)*w,y:a.y+(b.y-a.y)*t+(rand()-.5)*w,z:a.z+(b.z-a.z)*t+(rand()-.5)*w,color:j%6===0?'#f2d0a0':'#7cabdc',size:.025+rand()*.04});}for(let j=0;j<3;j++){const t=rand();galaxies.push(galaxy(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,a.z+(b.z-a.z)*t,.055+rand()*.10,j%3,rand()*Math.PI));}}
 for(const n of nodes){galaxies.push(galaxy(n.x,n.y,n.z,.25+rand()*.22,1));for(let i=0;i<4;i++)galaxies.push(galaxy(n.x+(rand()-.5)*1.4,n.y+(rand()-.5)*1.3,n.z+(rand()-.5),.08+rand()*.12,i%3,rand()*Math.PI));}
 return {spheres:[],points,orbits:[],galaxies,filaments:edges,labels:universe?[{x:0,y:8.5,z:0,text:'這是可觀測宇宙內的結構示意，不是宇宙的牆'}]:[{x:-6,y:8,z:0,text:'節點：星系群與星系團聚集'},{x:6,y:-6,z:0,text:'絲狀結構之間，有廣大的空洞'}]};}
