import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {sceneSpec,cosmicIds} from './cosmic-model.js';
import {galaxyStamp} from './galaxy-stamp.js';
import {createZoomMotion,layerTransform,zoomAt,clampProgress} from './cosmic-motion.js';
function earthTexture(){const c=document.createElement('canvas');c.width=256;c.height=128;const x=c.getContext('2d');if(!x)return null;const d=x.createImageData(256,128);for(let j=0;j<128;j++)for(let i=0;i<256;i++){const lat=(j/128-.5)*Math.PI,lon=i/256*Math.PI*2,n=Math.sin(lon*3+Math.sin(lat*5))+Math.sin(lat*6+lon*.6),polar=Math.abs(lat)>1.3;const color=polar?[194,217,227]:n>.6?[77,126,101]:[28,83,127],k=(j*256+i)*4;for(let t=0;t<3;t++)d.data[k+t]=color[t];d.data[k+3]=255;}x.putImageData(d,0,0);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
// Each layer shares Earth's observational anchor at (0,0,0). These display-space
// zoom stops are deliberately compressed, not physical metric coordinates.
export function anchoredSpec(i){const s=sceneSpec(i);if(i===0)return {...s,spheres:[],labels:[]};if(i===1)return {...s,spheres:[{x:-8,y:0,z:0,r:1.5,color:'#ffc167',label:'太陽'}],lines:[[-8,0,0,0,0,0]],labels:[{x:-4,y:1,z:0,text:'1 AU · 光約走 8 分 19 秒'}]};if(i===2){const radii=[.52,.72,1,1.5,3,4.5,6,8];return {...s,orbitCenter:-1,orbits:radii,spheres:[{x:-1,y:0,z:0,r:1.5/8,color:'#ffc167',label:'太陽'},...s.spheres.slice(1).filter((_,j)=>j!==2).map((p,j)=>{const k=j<2?j:j+1,r=radii[k];return {...p,x:-1+Math.cos(k*.9)*r,z:Math.sin(k*.9)*r,r:k>3?.15:.07};})],labels:[]};}if(i===3)return {...s,spheres:[{x:8,y:0,z:0,r:.18,color:'#e99074',label:'比鄰星'}],lines:[[0,0,0,8,0,0]],labels:[{x:4,y:1.3,z:0,text:'太陽附近 → 比鄰星：約 4.24 光年'}]};const shift=i===4?-5.2:i===5?3:0;return {...s,spheres:[],points:s.points.map(p=>({...p,x:p.x+shift})),galaxies:s.galaxies?.map(p=>({...p,x:p.x+shift})),labels:s.labels.map(p=>({...p,x:p.x+shift}))};}
export function buildCosmicLayer(spec,textures){const g=new THREE.Group();for(const a of spec.galaxies||[]){const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:textures[a.kind||0],transparent:true,opacity:1,depthWrite:false,blending:THREE.AdditiveBlending,rotation:a.angle||0}));sprite.position.set(a.x,a.y,a.z);sprite.scale.set(a.r*2,a.r*2,1);g.add(sprite);}if(spec.filaments){const positions=[];for(const [a,b] of spec.filaments)positions.push(a.x,a.y,a.z,b.x,b.y,b.z);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.add(new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:'#79aee4',transparent:true,opacity:.25,depthWrite:false,blending:THREE.AdditiveBlending})));}for(const p of spec.spheres){const m=new THREE.MeshStandardMaterial({color:p.color,roughness:1,emissive:p.color,emissiveIntensity:.35,transparent:true});const mesh=new THREE.Mesh(new THREE.SphereGeometry(p.r,32,20),m);mesh.position.set(p.x,p.y,p.z);g.add(mesh);}if(spec.points.length){const positions=[],colors=[];for(const p of spec.points){positions.push(p.x,p.y,p.z);const c=new THREE.Color(p.color);colors.push(c.r,c.g,c.b);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.add(new THREE.Points(geo,new THREE.PointsMaterial({size:.095,vertexColors:true,transparent:true,opacity:.85,depthWrite:false})));}for(const r of spec.orbits){const pts=Array.from({length:129},(_,n)=>new THREE.Vector3(Math.cos(n/128*Math.PI*2)*r+(spec.orbitCenter||0),0,Math.sin(n/128*Math.PI*2)*r));g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:'#7395af',transparent:true,opacity:.45})));}for(const l of spec.lines||[])g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...l.slice(0,3)),new THREE.Vector3(...l.slice(3))]),new THREE.LineBasicMaterial({color:'#aa9376',transparent:true,opacity:.7})));g.traverse(o=>{if(o.material)o.userData.baseOpacity=o.material.opacity;});return g;}
export function createCosmicView(host,{onMode,onProgress,reducedMotion=false,force2d=false}={}){
 host.dataset.reducedMotion=String(reducedMotion);const motion=createZoomMotion(0,reducedMotion),specs=Array.from({length:cosmicIds.length},(_,i)=>anchoredSpec(i));let renderer=null,scene,camera,controls,earth,anchor,raf=0,disposed=false,active=true,dirty=true,ctx=null,sized=false;const stamps=[0,1,2].map(galaxyStamp),textures=stamps.map(c=>{const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}),groups=[],overlay=document.createElement('div'),fallback=document.createElement('canvas');overlay.className='cosmic-labels';overlay.setAttribute('aria-hidden','true');fallback.className='cosmic-2d';fallback.setAttribute('aria-hidden','true');host.append(overlay);host.prepend(fallback);try{ctx=fallback.getContext('2d');}catch{}
 const originLabel=document.createElement('span');originLabel.className='earth-anchor-label';originLabel.textContent='地球觀測起點';overlay.append(originLabel);const layerLabels=specs.map((s,i)=>[...s.spheres.filter(p=>p.label).map(p=>({...p,text:p.label,y:p.y-p.r-.5})),...s.labels].map(p=>{const el=document.createElement('span');el.textContent=p.text;el._point=new THREE.Vector3(p.x,p.y,p.z);el._layer=i;overlay.append(el);return el;}));
 function fail(){if(renderer){renderer.dispose();renderer.domElement.remove();renderer=null;}fallback.hidden=false;onMode?.('2d');dirty=true;if(sized)resize();}
 try{if(force2d)throw Error('2D requested');renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;host.prepend(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','以地球觀測起點連續拉遠的三維示意。方向鍵切換尺度，滑桿連續縮放。');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(46,1,.01,10000);camera.position.set(0,13,23);controls=new OrbitControls(camera,renderer.domElement);renderer.domElement.style.touchAction='pan-y';controls.enableDamping=true;controls.enableZoom=false;controls.enablePan=false;controls.rotateSpeed=.55;scene.add(new THREE.AmbientLight('#ddefff',2));const light=new THREE.DirectionalLight('#e1efff',3);light.position.set(-5,5,8);scene.add(light);
 earth=new THREE.Mesh(new THREE.SphereGeometry(3.9,40,26),new THREE.MeshStandardMaterial({color:'#ffffff',roughness:1,map:earthTexture()}));scene.add(earth);anchor=new THREE.Mesh(new THREE.SphereGeometry(.035,12,8),new THREE.MeshBasicMaterial({color:'#ffdda4',transparent:true,opacity:0}));scene.add(anchor);
 for(let i=0;i<cosmicIds.length;i++){const g=buildCosmicLayer(specs[i],textures);scene.add(g);groups.push(g);}
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fail();});fallback.hidden=true;onMode?.('3d');}catch{fail();}
 let width=800,height=500,unit=20;function resize(){sized=true;width=host.clientWidth||800;height=host.clientHeight||500;unit=Math.min(width/23,height/23);if(renderer){renderer.setSize(width,height);camera.aspect=width/height;camera.fov=camera.aspect<1?65:46;camera.updateProjectionMatrix();}else if(ctx){const dpr=Math.min(globalThis.devicePixelRatio||1,1.5);fallback.width=width*dpr;fallback.height=height*dpr;fallback.style.width=width+'px';fallback.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);}dirty=true;}
 function point2d(p,scale){return [width/2+p.x*unit*scale,height/2+(p.z*.35-p.y*.8)*unit*scale];}
 function sphere2d(p,scale,opacity,isEarth=false){const [x,y]=point2d(p,scale),r=p.r*unit*scale;if(r<.06||x+r<0||x-r>width||y+r<0||y-r>height||r>10000)return;ctx.globalAlpha=opacity;const grad=ctx.createRadialGradient(x-r*.35,y-r*.4,r*.05,x,y,r);grad.addColorStop(0,p.color);grad.addColorStop(.6,p.color);grad.addColorStop(1,'#07101c');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(isEarth&&r>3){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();ctx.globalAlpha=opacity*.55;ctx.fillStyle='#91b2a1';for(let a=0;a<5;a++){ctx.beginPath();ctx.ellipse(x+Math.sin(a*2.3)*r*.55,y+Math.cos(a*1.8)*r*.5,r*.2,r*.11,a,0,Math.PI*2);ctx.fill();}ctx.restore();}}
 function draw2d(p){if(!ctx)return;ctx.clearRect(0,0,width,height);let seed=17;ctx.globalAlpha=1;for(let n=0;n<100;n++){seed=seed*16807%2147483647;const x=seed/2147483647*width;seed=seed*16807%2147483647;ctx.fillStyle='#adbed144';ctx.fillRect(x,seed/2147483647*height,1,1);}for(let i=cosmicIds.length-1;i>=1;i--){const t=layerTransform(i,p),spec=specs[i];if(!t.visible)continue;ctx.globalAlpha=t.opacity;if(spec.filaments){for(const [a,b] of spec.filaments){const [x,y]=point2d(a,t.scale),[x2,y2]=point2d(b,t.scale);ctx.strokeStyle='#6392ca22';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle='#92bdea66';ctx.lineWidth=.75;ctx.stroke();}}ctx.save();ctx.globalCompositeOperation='screen';for(const a of spec.galaxies||[]){const [x,y]=point2d(a,t.scale),r=Math.max(1.8,a.r*unit*t.scale);if(x+r<0||x-r>width||y+r<0||y-r>height||r>10000)continue;ctx.save();ctx.translate(x,y);ctx.rotate(a.angle||0);ctx.drawImage(stamps[a.kind||0],-r,-r,2*r,2*r);ctx.restore();}ctx.restore();for(const r of spec.orbits){const [x,y]=point2d({x:spec.orbitCenter||0,y:0,z:0},t.scale);ctx.strokeStyle='#7795af77';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(x,y,r*unit*t.scale,r*unit*t.scale*.35,0,0,Math.PI*2);ctx.stroke();}for(const l of spec.lines||[]){const [x,y]=point2d({x:l[0],y:l[1],z:l[2]},t.scale),[x2,y2]=point2d({x:l[3],y:l[4],z:l[5]},t.scale);ctx.strokeStyle='#d4b27b88';ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();ctx.setLineDash([]);}for(const a of spec.points){const [x,y]=point2d(a,t.scale);if(x<0||x>width||y<0||y>height)continue;ctx.fillStyle=a.color;ctx.beginPath();ctx.arc(x,y,Math.max(.45,Math.min(3,(a.size||.04)*unit*Math.sqrt(t.scale))),0,Math.PI*2);ctx.fill();}for(const a of spec.spheres)sphere2d(a,t.scale,t.opacity);}
 const earthScale=Math.exp(-zoomAt(p));sphere2d({x:0,y:0,z:0,r:3.9,color:'#4586ad'},earthScale,1,true);if(3.9*unit*earthScale<2.8){ctx.globalAlpha=1;ctx.strokeStyle='#efc58f';ctx.lineWidth=1;ctx.beginPath();ctx.arc(width/2,height/2,4,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#efc58f';ctx.fillRect(width/2-1,height/2-1,2,2);}ctx.globalAlpha=1;
 }
 function render(p){host.dataset.zoomProgress=p.toFixed(4);host.dataset.zoomTarget=motion.target.toFixed(4);host.dataset.zoomAnimating=String(motion.moving);const z=zoomAt(p),e=Math.exp(-z);if(renderer){for(let i=0;i<groups.length;i++){const t=layerTransform(i,p),g=groups[i];g.visible=t.visible;g.scale.setScalar(t.scale);g.traverse(o=>{if(o.material)o.material.opacity=o.userData.baseOpacity*t.opacity;});}earth.scale.setScalar(e);anchor.material.opacity=3.9*unit*e<2.8?1:0;controls.update();camera.updateMatrixWorld();renderer.render(scene,camera);}else draw2d(p);
 for(let i=0;i<layerLabels.length;i++){const t=layerTransform(i,p);for(const el of layerLabels[i]){const weight=Math.max(0,1-Math.abs(p-i)*1.5);el.hidden=weight<.08;if(el.hidden)continue;let x,y;if(renderer){const v=el._point.clone().multiplyScalar(t.scale).project(camera);x=(v.x*.5+.5)*width;y=(-v.y*.5+.5)*height;}else [x,y]=point2d(el._point,t.scale);el.style.left=x+'px';el.style.top=y+'px';el.style.opacity=String(weight);}}originLabel.style.left=width/2+'px';originLabel.style.top=height/2+Math.min(height*.3,3.9*unit*e)+8+'px';originLabel.textContent=p<.5?'地球':p<2?'地球觀測起點':'我們在這個方向 · 標記已放大';onProgress?.(p,motion.target,motion.moving);
 }
 function frame(now){if(disposed)return;raf=requestAnimationFrame(frame);const moving=motion.moving,p=motion.advance(now);if((active&&!document.hidden)&&(dirty||moving||renderer)){render(p);dirty=false;}}
 const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;observer?.observe(host);const visible=typeof IntersectionObserver!=='undefined'?new IntersectionObserver(entries=>{active=entries[0].isIntersecting;if(active)dirty=true;}):null;visible?.observe(host);resize();render(0);raf=requestAnimationFrame(frame);
 return {setStage(n,{immediate=false,scrub=false}={}){motion.aim(clampProgress(n),performance.now(),{immediate,scrub});dirty=true;if(immediate||reducedMotion)render(motion.value);},getProgress(){return motion.advance(performance.now());},getTarget(){return motion.target;},resetView(){if(camera){camera.position.set(0,13,23);controls.target.set(0,0,0);controls.update();}},dispose(){disposed=true;cancelAnimationFrame(raf);observer?.disconnect();visible?.disconnect();controls?.dispose();if(scene)scene.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});textures.forEach(t=>t.dispose());renderer?.dispose();host.replaceChildren();}};
}
