import data from './cosmic-data.json';
import {clampProgress} from './cosmic-motion.js';
import {createCosmicView} from './cosmic-scene.js';
export function initCosmic(){
 const $=s=>document.querySelector(s),{stages}=data;let index=0,target=0,scrubbing=false;const reducedMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
 $('#cosmic-steps').innerHTML=stages.map((s,i)=>`<button data-cosmic="${i}" aria-current="false"><small>${String(i+1).padStart(2,'0')}</small>${s.name}</button>`).join('');
 const view=createCosmicView($('#cosmic-stage'),{reducedMotion,force2d:new URLSearchParams(location.search).has('no3d'),onProgress:(p,t,moving)=>{if(!scrubbing)$('#cosmic-range').value=String(p);$('#cosmic-stage').setAttribute('aria-busy',String(moving));$('#cosmic-scale').textContent=stages[Math.round(p)].scaleLabel;$('#cosmic-visual-note').textContent=p>=5?'星系形狀、數量、位置與絲線皆為教學示意，非真實星圖':'藝術化空間示意，請以標示數值為準';$('#cosmic-motion-status').textContent=moving?`${t>=p?'正在拉遠':'正在拉近'} · ${stages[Math.floor(p)].name} → ${stages[Math.min(stages.length-1,Math.ceil(p))].name}`:'觀測起點：地球 · 不是宇宙的中心';},onMode:mode=>{$('#cosmic-mode').textContent=mode==='3d'?'✦ 3D 尺度導覽':'✦ 2D 尺度導覽';}});
 function show(next,save=false,{immediate=false,scrub=false}={}){target=clampProgress(next);index=Math.round(target);const s=stages[index];view.setStage(target,{immediate,scrub});$('#cosmic-counter').textContent=`${String(index+1).padStart(2,'0')} / ${String(stages.length).padStart(2,'0')}`;$('#cosmic-scale').textContent=s.scaleLabel;if(immediate||reducedMotion)$('#cosmic-range').value=String(target);$('#cosmic-range').setAttribute('aria-valuetext',s.name+'，'+s.scaleLabel);$('#cosmic-range-name').textContent=s.name;$('#cosmic-prev').disabled=target===0;$('#cosmic-next').disabled=target===stages.length-1;document.querySelectorAll('[data-cosmic]').forEach(b=>b.setAttribute('aria-current',Number(b.dataset.cosmic)===index?'step':'false'));$('#cosmic-detail').innerHTML=`<p class="eyebrow">${String(index+1).padStart(2,'0')} / 目的尺度 · ${s.kicker}</p><h3>${s.title}</h3><div class="cosmic-distance">${s.scaleLabel}</div><div class="cosmic-copy">${s.facts.map(f=>`<p>${f}</p>`).join('')}</div><p class="cosmic-caution">${s.caution}</p><div class="cosmic-light"><span>光與時間</span>${s.lightTime}</div><a class="source" href="${s.source}" target="_blank" rel="noopener">查看官方資料 ↗</a>${s.sources?.length>1?`<div class="cosmic-extra-sources">${s.sources.slice(1).map((url,i)=>`<a href="${url}" target="_blank" rel="noopener">延伸來源 ${i+1} ↗</a>`).join(' · ')}</div>`:''}`;if(save){const u=new URL(location.href);u.searchParams.set('cosmic',String(Number(target.toFixed(2))));if(u.href!==location.href)history.pushState(null,'',u);}}
 function step(direction){const p=view.getProgress(),t=view.getTarget();const next=direction>0?(t<p?Math.ceil(p):Math.floor(t)+1):(t>p?Math.floor(p):Math.ceil(t)-1);show(clampProgress(next),true);}
 $('#cosmic-prev').addEventListener('click',()=>step(-1));$('#cosmic-next').addEventListener('click',()=>step(1));document.querySelectorAll('[data-cosmic]').forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.cosmic),true)));$('#cosmic-range').addEventListener('pointerdown',()=>scrubbing=true);window.addEventListener('pointerup',()=>scrubbing=false);$('#cosmic-range').addEventListener('input',e=>show(Number(e.target.value),false,{scrub:true}));$('#cosmic-range').addEventListener('change',()=>{scrubbing=false;show(target,true,{scrub:true});});$('#cosmic-reset').addEventListener('click',()=>{view.resetView();show(0,true,{immediate:true});});$('#return-solar').addEventListener('click',()=>{show(view.getProgress(),false,{immediate:true});document.querySelector('#planet-nav [data-body=earth]').click();});
 $('#cosmic-stage').addEventListener('keydown',e=>{if(['ArrowRight','ArrowUp','ArrowLeft','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();if(e.key==='Home')show(0,true);else if(e.key==='End')show(stages.length-1,true);else step(['ArrowRight','ArrowUp'].includes(e.key)?1:-1);}});$('#cosmic-stage').tabIndex=0;
 window.addEventListener('popstate',()=>show(clampProgress(new URLSearchParams(location.search).get('cosmic')),false,{immediate:true}));
 show(clampProgress(new URLSearchParams(location.search).get('cosmic')),false,{immediate:true});
 return {show,index:()=>index,dispose:()=>view.dispose()};
}
