import './styles.css';
import data from './data.json';
import {format,ratio} from './model.js';
import {createSolarScene} from './scene.js';
const {planets,sun}=data,bodies=[sun,...planets],$=s=>document.querySelector(s);let selected='earth',scene=null,flat=false,failed=false,paused=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false,metric='diameterKm';
const orb=(b,px)=>`<span class="orb ${b.id}" style="--body-color:${b.color};--diameter:${px}px" aria-hidden="true"></span>`;
$('#planet-nav').innerHTML=bodies.map(b=>`<button data-body="${b.id}" aria-pressed="false"><span class="nav-dot" style="--body-color:${b.color}"></span>${b.name}<small>${b.en.toUpperCase()}</small></button>`).join('');
$('#flat').innerHTML=bodies.map((b,i)=>`<button class="flat-body" data-body="${b.id}" aria-label="探索${b.name}">${orb(b,i===0?70:Math.max(15,Math.sqrt(b.diameterKm/planets[4].diameterKm)*52))}<span>${b.name}</span></button>`).join('');
function select(id,save=true){const b=bodies.find(x=>x.id===id);if(!b)return;selected=id;scene?.select(id);document.querySelectorAll('[data-body]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.body===id)));$('#detail').innerHTML=`<div class="detail-index">${id==='sun'?'THE STAR':String(bodies.indexOf(b)).padStart(2,'0')+' / 08'} · COSMIC FIELD NOTES</div><div class="detail-heading"><div><h2>${b.name}</h2><small>${b.en.toUpperCase()}</small></div>${orb(b,65)}</div><span class="type">${b.type}</span><p class="tagline">${b.tagline}</p><ul class="facts">${b.facts.map(f=>`<li>${f}</li>`).join('')}</ul><div class="stats"><div class="stat"><span>平均直徑</span><b>約 ${format(Math.round(b.diameterKm))} km</b></div><div class="stat"><span>軌道半長軸</span><b>${b.distanceAU===null?'—（中央恆星）':format(b.distanceAU)+' AU'}</b></div><div class="stat"><span>公轉週期</span><b>${b.orbitDays===null?'—（不適用）':format(b.orbitDays)+' 地球日'}</b></div></div><a class="source" href="${b.source}" target="_blank" rel="noopener">NASA ${b.name}資料 ↗</a>`;if(save){const u=new URL(location.href);u.searchParams.set('planet',id);history.pushState(null,'',u);}}
document.querySelectorAll('[data-body]').forEach(b=>b.addEventListener('click',()=>select(b.dataset.body)));window.addEventListener('popstate',()=>select(new URLSearchParams(location.search).get('planet')||'earth',false));
function setFlat(value){flat=value;$('#flat').hidden=!flat;scene?.setVisible(!flat);$('#mode').textContent=flat?'切換 3D 探索':'切換 2D 導覽';$('#mode').disabled=failed;$('#interaction-hint').textContent=flat?'點選天體或使用下方按鈕閱讀知識卡':'拖曳旋轉 · 滾輪／雙指縮放 · 點選行星';for(const id of ['zoom-in','zoom-out','reset','pause','speed'])$('#'+id).disabled=flat;$('#time-label').textContent=flat?'2D 靜態導覽':`1 秒 = ${20*Number($('#speed').value)} 地球日`;}
function fail(){document.querySelectorAll('#stage canvas').forEach(c=>c.hidden=true);$('#labels').hidden=true;failed=true;setFlat(true);$('#fallback').hidden=false;$('#mode').textContent='目前為 2D 導覽';}
try{if(new URLSearchParams(location.search).has('no3d'))throw Error('Explicit fallback');scene=createSolarScene($('#stage'),bodies,id=>select(id),fail);scene.setPaused(paused);setFlat(false);}catch(e){fail();}
$('#mode').addEventListener('click',()=>setFlat(!flat));$('#zoom-in').addEventListener('click',()=>scene?.zoom(.8));$('#zoom-out').addEventListener('click',()=>scene?.zoom(1.25));$('#reset').addEventListener('click',()=>scene?.reset());
function updatePause(){scene?.setPaused(paused);$('#pause').textContent=paused?'▶ 開始公轉':'Ⅱ 暫停公轉';$('#pause').setAttribute('aria-pressed',String(paused));}$('#pause').addEventListener('click',()=>{paused=!paused;updatePause();});$('#speed').addEventListener('change',()=>{scene?.setSpeed(Number($('#speed').value));$('#time-label').textContent=`1 秒 = ${20*Number($('#speed').value)} 地球日`;});updatePause();
const metrics={diameterKm:{unit:'km',note:'平均直徑比較。長條共用線性比例，最長為木星；採體積等效平均半徑 × 2，非赤道直徑。'},distanceAU:{unit:'AU',note:'軌道半長軸比較。長條共用線性比例；這是軌道尺度，並非此刻日距。1 AU 約 1.496 億公里。'},orbitDays:{unit:'地球日',note:'恆星公轉週期比較。長條共用線性比例，內行星的短條很小是正常的；數字仍完整顯示。'}};
function chart(){const m=metrics[metric],max=Math.max(...planets.map(b=>b[metric]));$('#compare-note').textContent=m.note;$('#chart').innerHTML=planets.map(b=>`<div class="bar-row"><span>${b.name}</span><div class="bar-track" aria-hidden="true"><i style="--body-color:${b.color};width:${ratio(b[metric],max)*100}%"></i></div><span class="bar-value">${format(metric==='diameterKm'?Math.round(b[metric]):b[metric])} ${m.unit}</span></div>`).join('');document.querySelectorAll('[data-metric]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.metric===metric)));}
document.querySelectorAll('[data-metric]').forEach(b=>b.addEventListener('click',()=>{metric=b.dataset.metric;chart();}));$('#size-row').innerHTML=planets.map(b=>`<div class="size-item">${orb(b,b.diameterKm/planets[4].diameterKm*120)}<span>${b.name}</span></div>`).join('');const initial=new URLSearchParams(location.search).get('planet');select(bodies.some(b=>b.id===initial)?initial:'earth',false);chart();

// Scale journey uses independent layer views; the existing solar simulator remains unchanged.
import {initCosmic} from './cosmic.js';
initCosmic();
