import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {orbitPosition,orbitRadii,displayRadii,TAU} from './model.js';
export function makeOrbit(radius){return new THREE.BufferGeometry().setFromPoints(Array.from({length:181},(_,i)=>new THREE.Vector3(Math.cos(i/180*TAU)*radius,0,Math.sin(i/180*TAU)*radius)));}
export function createSolarScene(stage,bodies,onSelect,onLost){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;stage.prepend(renderer.domElement);const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label','三維太陽系。方向鍵旋轉，加減鍵縮放。也可使用畫布下方行星按鈕。');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(43,1,.1,600);camera.position.set(0,43,51);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=9;controls.maxDistance=110;controls.maxPolarAngle=Math.PI*.95;
 scene.add(new THREE.AmbientLight('#cfdef0',1.3));const light=new THREE.PointLight('#ffddad',160,130,1);scene.add(light);
 const sphere=new THREE.SphereGeometry(1,48,32),meshes=[],rings=[];const labels=document.getElementById('labels');
 // Analytic procedural shading: no downloaded photos or external artwork.
 const fragment=`varying vec3 vNormal; varying vec3 vWorld; varying vec3 vLocal; uniform vec3 base; uniform float kind; uniform float seed; float noise(vec3 p){return sin(p.x*12.+sin(p.z*8.))*sin(p.y*15.+sin(p.x*7.));} void main(){vec3 p=vLocal;float n=noise(p*2.+seed);vec3 col=base; if(kind==1.){float land=sin(p.x*5.+sin(p.z*6.))+sin(p.y*8.+p.z*3.);col=mix(vec3(.025,.22,.43),vec3(.19,.4,.25),smoothstep(.25,.6,land));float cloud=smoothstep(.65,.93,noise(p*1.4+2.));col=mix(col,vec3(.88,.92,.91),cloud*.65);if(abs(p.y)>.89)col=mix(col,vec3(.88,.93,.95),.8);}else if(kind==2.){float bands=sin(p.y*35.+sin(p.x*5.)*.8);col*=.76+.24*bands;col+=vec3(.1,.06,.025)*n;}else if(kind==3.){col*=.9+.12*sin(p.y*18.);}else{col*=.83+.17*n;}float lit=.26+.74*max(dot(normalize(vNormal),normalize(-vWorld)),0.);if(kind==4.){lit=1.25;col+=vec3(.1,.035,0.)*n;}gl_FragColor=vec4(col*lit,1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>}`;
 bodies.forEach((b,i)=>{const kind=b.id==='earth'?1:['jupiter','saturn'].includes(b.id)?2:['uranus','neptune','venus'].includes(b.id)?3:b.id==='sun'?4:0;const material=new THREE.ShaderMaterial({uniforms:{base:{value:new THREE.Color(b.color)},kind:{value:kind},seed:{value:i*3.21}},vertexShader:'varying vec3 vNormal;varying vec3 vWorld;varying vec3 vLocal;void main(){vLocal=position;vNormal=mat3(modelMatrix)*normal;vWorld=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(vWorld,1.);}',fragmentShader:fragment});const mesh=new THREE.Mesh(sphere,material);mesh.scale.setScalar(i===0?2.5:displayRadii[i-1]);mesh.userData.id=b.id;scene.add(mesh);meshes.push(mesh);const label=document.createElement('span');label.className='planet-label';label.textContent=b.name;labels.append(label);mesh.userData.label=label;
 if(i>0){const ring=new THREE.Line(makeOrbit(orbitRadii[i-1]),new THREE.LineBasicMaterial({color:'#6f8295',transparent:true,opacity:.25}));scene.add(ring);rings.push(ring);}
 if(b.id==='saturn'){const ring=new THREE.Mesh(new THREE.RingGeometry(1.5,2.3,96),new THREE.MeshBasicMaterial({color:'#bfb093',transparent:true,opacity:.63,side:THREE.DoubleSide}));ring.rotation.x=Math.PI/2-.4;mesh.add(ring);}
 });
 const glow=new THREE.Mesh(new THREE.SphereGeometry(2.72,48,32),new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.BackSide,vertexShader:'varying vec3 n;varying vec3 p;void main(){n=normalize(normalMatrix*normal);vec4 q=modelViewMatrix*vec4(position,1.);p=q.xyz;gl_Position=projectionMatrix*q;}',fragmentShader:'varying vec3 n;varying vec3 p;void main(){float f=pow(1.-abs(dot(normalize(n),normalize(-p))),2.);gl_FragColor=vec4(1.,.5,.12,f*.45);}'}));scene.add(glow);
 let seed=8721;const rand=()=>{seed=seed*16807%2147483647;return seed/2147483647;},positions=[];for(let i=0;i<1000;i++){let a=rand()*TAU,z=rand()*2-1,r=170;positions.push(r*Math.sqrt(1-z*z)*Math.cos(a),r*z,r*Math.sqrt(1-z*z)*Math.sin(a));}const stars=new THREE.BufferGeometry();stars.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:'#b9cee0',size:.18,transparent:true,opacity:.65})));
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null,days=0,paused=false,speed=1,running=true,last=performance.now(),selected='earth',visible=true;const visibility=typeof IntersectionObserver!=='undefined'?new IntersectionObserver(entries=>visible=entries[0].isIntersecting):null;visibility?.observe(stage);
 canvas.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);canvas.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<6){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(meshes,false)[0];if(hit)onSelect(hit.object.userData.id);}down=null;});
 function zoom(f){camera.position.multiplyScalar(f).clampLength(9,110);controls.update();}function reset(){camera.position.set(0,43,51);controls.target.set(0,0,0);controls.update();}
 canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key))return;e.preventDefault();if(e.key==='+'||e.key==='=')zoom(.9);else if(e.key==='-')zoom(1.1);else{const s=new THREE.Spherical().setFromVector3(camera.position);s.theta+=e.key==='ArrowLeft'?-.12:e.key==='ArrowRight'?.12:0;s.phi=Math.max(.1,Math.min(Math.PI*.95,s.phi+(e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0)));camera.position.setFromSpherical(s);controls.update();}});
 const resize=new ResizeObserver(()=>{const w=stage.clientWidth,h=stage.clientHeight;camera.aspect=w/h;camera.fov=camera.aspect<1?63:43;camera.updateProjectionMatrix();renderer.setSize(w,h);});resize.observe(stage);
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();running=false;canvas.hidden=true;labels.hidden=true;onLost();});
 const vector=new THREE.Vector3();function frame(now){if(!running)return;requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.06);last=now;if(document.hidden||!visible)return;if(!paused)days+=dt*20*speed;meshes.forEach((mesh,i)=>{if(i)mesh.position.fromArray(orbitPosition(i-1,days,bodies[i].orbitDays));if(!paused)mesh.rotation.y+=dt*.04;vector.copy(mesh.position).project(camera);const label=mesh.userData.label;label.style.left=(vector.x*.5+.5)*stage.clientWidth+'px';label.style.top=(-vector.y*.5+.5)*stage.clientHeight+'px';label.hidden=vector.z>1||vector.z< -1;label.classList.toggle('selected',mesh.userData.id===selected);});controls.update();renderer.render(scene,camera);}requestAnimationFrame(frame);
 return {select(id){selected=id;},zoom,reset,setPaused(v){paused=v;},setSpeed(v){speed=v;},setVisible(v){canvas.hidden=!v;labels.hidden=!v;},dispose(){running=false;visibility?.disconnect();resize.disconnect();controls.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose();});renderer.dispose();canvas.remove();labels.replaceChildren();}};
}
